---
resources:
- name: windowsstem
  type: git
  source:
    uri: https://github.com/orangeglasses/bosh-windows-vsphere-stemcell-pipeline.git
- name: BOSHresources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git

jobs:
- name: prepare-clone
  public: true
  plan:
  - get: windowsstem
  - task: clone
    file: windowsstem/pipeline/clonevm/clonevm.yml
    params: 
        VROUSER: {{vro_user}}
        VROPASS: {{vro_pass}}
        VROENDPOINT: {{vro_endpoint}}
- name: addBOSHresource
  public: true
  plan:
  - get: BOSHresources
  - get: windowsstem
  - task: buildPSModules
    file: windowsstem/pipeline/buildPSModules/buildPSModules.yml
    params:
        VERSION: "1056.0"
  - task: copyPSModules
    file: windowsstem/pipeline/buildPSModules/copyPSModules.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}
