---
resource_types:
  - name: redis
    type: docker-image
    source:
      repository: cfcommunity/redis-resource
  - name: file-url
    type: docker-image
    source:
      repository: pivotalservices/concourse-curl-resource
      tag: latest

resources:
- name: windowsstem
  type: git
  source:
    uri: https://github.com/orangeglasses/bosh-windows-vsphere-stemcell-pipeline.git
- name: BOSHresources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: redis-values
  type: redis
  source:
    host: {{redis_endpoint}}
    password: {{redis_password}}
    keys:
      - cloneip
- name: lgpo
  type: file-url
  source:
    url: https://msdnshared.blob.core.windows.net/media/2016/09/LGPOv2-PRE-RELEASE.zip
    filename: lgpo.zip

jobs:
- name: createVM
  public: true
  plan:
  - get: windowsstem
  - task: clone
    file: windowsstem/pipeline/clonevm/clonevm.yml
    params: 
        VROUSER: {{vro_user}}
        VROPASS: {{vro_pass}}
        VROENDPOINT: {{vro_endpoint}}
  - put: redis-values
    params: {from: cloneip}


- name: addBOSHmodules
  public: true
  plan:
  - aggregate: 
        - get: BOSHresources
        - get: windowsstem
        - get: redis-values
          passed: [createVM]
  - task: buildPSModules
    file: windowsstem/pipeline/buildPSModules/buildPSModules.yml
    params:
        VERSION: {{version}}
  - task: copyPSModules
    file: windowsstem/pipeline/buildPSModules/copyPSModules.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}

- name: addBOSHagent
  public: true
  plan:
  - aggregate:
        - get: BOSHresources
        - get: windowsstem
        - get: redis-values
          passed: [createVM]
  - task: buildAgent
    file: windowsstem/pipeline/addAgent/buildAgent.yml
    params: 
        VERSION: {{version}}
  - task: copyAgent
    file: windowsstem/pipeline/addAgent/copyAgent.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}

- name: prepareCell
  public: true
  plan:
  - get: windowsstem
  - get: redis-values
    passed: [createVM, addBOSHmodules, addBOSHagent]
  - task: prepareCell
    file: windowsstem/pipeline/prepareCell/prepareCell.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}
        VERSION: {{version}}

- name: sysprep
  public: true
  plan:
  - get: windowsstem
  - get: redis-values
    passed: [createVM, addBOSHmodules, addBOSHagent, prepareCell]
  - get: lgpo
  - task: sysprep
    file: windowsstem/pipeline/sysprep/sysprep.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}
        ORG: {{organisation}}
        PRODUCTKEY: {{productkey}}

- name: preparestemcell
  public: true
  plan:
  - get: windowsstem
    passed: [sysprep]
  - task: extractOVA
    file: windowsstem/pipeline/preparestemcell/extractOVA.yml
    params:
        VCUSER: {{vc_user}}
        VCPASS: {{vc_pass}}        
        VCHOST: {{vc_host}}

