---
resource_types:
  - name: redis
    type: docker-image
    source:
      repository: cfcommunity/redis-resource
  - name: file-url
    type: docker-image
    source:
      repository: pivotalservices/concourse-curl-resource
      tag: latest

resources:
- name: schedule  
  type: time  
  source:    
#    interval: 24h    
    start: ((start_time))    
    stop: ((stop_time))    
    location: Europe/Amsterdam    
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
- name: windowsstem
  type: git
  source:
    uri: https://github.com/orangeglasses/bosh-windows-vsphere-stemcell-pipeline.git
- name: BOSHresources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: redis-values
  type: redis
  source:
    host: {{redis_endpoint}}
    password: {{redis_password}}
    port: {{redis_port}}
    keys:
      - cloneip
- name: stembuild
  type: file-url # can't use the github-release-resource as stembuild doesn't use semver compliant versions for releases
  source:
    url: https://github.com/pivotal-cf-experimental/stembuild/releases/download/0.13/stembuild_linux_amd64
    filename: stembuild
- name: lgpo
  type: file-url
  source:
    url: https://msdnshared.blob.core.windows.net/media/2016/09/LGPOv2-PRE-RELEASE.zip
    filename: lgpo.zip
- name: release
  type: s3
  source:
    access_key_id: {{s3_user}}
    secret_access_key: {{s3_pass}}
    disable_ssl: true
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz

jobs:
- name: createVM
  public: true
  plan:
  - get: schedule
    trigger: true
  - get: windowsstem
  - task: clone
    file: windowsstem/pipeline/clonevm/clonevm.yml
    params: 
        VROUSER: {{vro_user}}
        VROPASS: {{vro_pass}}
        VROENDPOINT: {{vro_endpoint}}
        CLONEHOST: {{clone_host}}
        CLONECLUSTER: {{clone_cluster}}
        BASEVM: {{baseVM}}
  - put: redis-values
    params: {from: cloneip}


- name: addBOSHmodules
  public: true
  plan:
  - aggregate: 
        - get: schedule
          trigger: true
        - get: BOSHresources
        - get: windowsstem
        - get: redis-values
          passed: [createVM]
  - task: buildPSModules
    file: windowsstem/pipeline/buildPSModules/buildPSModules.yml
    params:
        VERSION: {{version}}
  - task: copyPSModules
    file: windowsstem/pipeline/buildPSModules/copyPSModules.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}

- name: addBOSHagent
  public: true
  plan:
  - aggregate:
        - get: schedule
          trigger: true
        - get: BOSHresources
        - get: windowsstem
        - get: redis-values
          passed: [createVM]
  - task: buildAgent
    file: windowsstem/pipeline/addAgent/buildAgent.yml
    params: 
        VERSION: {{version}}
  - task: copyAgent
    file: windowsstem/pipeline/addAgent/copyAgent.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}

- name: prepareCell
  public: true
  plan:
  - get: schedule
    trigger: true
  - get: windowsstem
  - get: redis-values
    passed: [addBOSHmodules, addBOSHagent]
  - task: prepareCell
    file: windowsstem/pipeline/prepareCell/prepareCell.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}
        VERSION: {{version}}
        SKIPOPT: {{skip_optimization}}

- name: sysprep
  public: true
  plan:
  - get: schedule
    trigger: true
  - get: windowsstem
  - get: redis-values
    passed: [prepareCell]
  - get: lgpo
  - task: sysprep
    file: windowsstem/pipeline/sysprep/sysprep.yml
    params:
        VMUSER: {{vm_user}}
        VMPASS: {{vm_pass}}
        ORG: {{organisation}}
        PRODUCTKEY: {{productkey}}

- name: preparestemcell
  public: true
  plan:
  - aggregate: 
        - get: schedule
          trigger: true
        - get: stembuild
        - get: windowsstem
        - get: BOSHresources
        - get: redis-values
          passed: [sysprep]
  - task: extractOVA
    file: windowsstem/pipeline/preparestemcell/extractOVA.yml
    params:
        VCUSER: {{vc_user}}
        VCPASS: {{vc_pass}}        
        VCHOST: {{vc_host}}
        VCDC: {{vc_dc}}
        VCVMFOLDER: {{vc_vmfolder}}
  - task: buildstem
    file: windowsstem/pipeline/preparestemcell/buildstem.yml
    params:
        VERSION: {{version}}
  - put: release
    params:
        file: stemdir/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
